### PR TITLE
Update dependencies

### LINKED ISSUE #329: Need to fix Koa integration tests on Node v4
KoA integration tests are broken on node 4. seems like koa uses es6 features.
we need to dig deeper to understand what was changed exactly, and make sure that the latest supported koa for node 4 i supported by us as well.

Temporary W/A which just disables Koa tests on node v4: #328

### PR DESCRIPTION
**Pull request by DxCx**
Closes #348
Closes #343
Closes #329 
@helfer @nnance @bkinsey808

Koa Issue = pending @helfer decision on #329

### CODE REVIEW

**Comment by helfer** [comment]
@DxCx @nnance let's drop Koa backwards compatibility and then release a new minor version of graphql-server that no longer supports Koa on Node 4 and 6. If someone is using it and would like that to keep working, we can always let them do that.

**Comment by nnance** [comment]
@DxCx I think we are working on the same thing right now
I was trying to fix the koa config in your branch to get your branch working
I talked to @helfer earlier and we had decided to keep node 6 support for 6
which I think is possible if we keep the older version of the body parser.

**Comment by DxCx** [comment]
branch is working now @nnance

**Comment by nnance** [comment]
@DxCx @helfer I am merging this PR as.a breaking change for KOA users.  I added a comment in the changelog

**Pull request merged**
