### PR TITLE
GraphQL-server websocket support

### LINKED ISSUE #222: Graphiql fetcher observable for subscriptions
Currently only uses the fetch API, but would be great to have graphiql's `fetcher` to return an Observable to support testing subscriptions.
Details here: https://github.com/graphql/graphiql/pull/104

Hoping to put a PR together, but want to get this documented in-case someone beats me to it 😄

### LINKED ISSUE #272: ws Network Interface Integration
Hi All,

I've been speaking with @helfer and we got into agreement that i should add a pure websocket integration.
before writing anything, i want to post here some mini-design to share my thoughts and hear some feedback.

**package name**: i was thinking about `graphql-server-ws`, then the function will be called `graphqlWs`.

**how to use it**:
So, i don't see any reason why not having the same interface as our other packages, therefore:
```typescript
import { graphqlWs } from "graphql-server-ws";
import { Server as WsServer } from "ws";
import { Schema } from './schema';
import { graphiqlExpress } from "graphql-server-express";

let app = express();
app.use("/graphiql", graphiqlExpress({
    endpointURL: `ws://localhost:3000/graphql`,
}));
let server = app.listen(3000, () => {
    let wss = new WsServer({ server: server });
    wss.on("connection", graphqlWs((ws) => {
        // The user can basically use any information he pleases too from ws connection object.
        const location = url.parse(ws.upgradeReq.url, true);

        // Multiplex ws connections by path.
        switch ( location.pathname ) {
           case "/graphql": // Same path graphiql is pointed to
               return {
                   context: {},
                   schema: Schema,
               };
           default:
               ws.terminate();
               return undefined;
        }
    });
});
```
NOTE: One more options is to do the multiplexing internally, but it breaks abit the similarity to other interfaces, and it will look like:
```typescript
    wss.on("connection", graphqlWs({
      "/graphql": (ws) => {
          // user can still use any information he pleases to make descisions.
          return {
               context: {},
               schema: Schema,
          };
        },
    });
```

**underlaying protocol**:
so, as i can see it, there is no much difference between using HTTP POST as a transport, or a websocket.

the main difference are:
1. websocket remains opens therefore you can send more then one request. 
2. because of the above, batching is redundant and there is no reason to support it.
3. websocket needs the ability to update older response.
4. client of the websocket should have the ability to cancel/close open request.

to solve this, i suggest to add the following fields to request:
1. `id` field - shall be used to respond.
2. `action` field - one of the following values:
  - request - default value incase action is missing, will trigger a new request,
                     when used, `query`, `variables` and `operationName` will be used.
  - cancel   - cancel or stop updates for Query Id, only `id` field is being used.
```typescript
interface WebsocketGraphqlRequest {
  id: number; // Per socket increasing number
  action?: "request" | "cancel";
  query?: string; // GraphQL Printed Query.
  variables?: any; // GraphQL variables.
  operationName?: string; // GraphQL operationName
}
```

also, the response should also add response type and id, so it will look like:
```typescript
interface WebsocketGraphqlResponse {
  id: number;
  type: "init" | "update" | "error" | "complete"
  payload: any; // standard object (data/errors) incase of init, 
                         // Error for error type
                         // diff object incase of update
                         // empty incase of complete.
}
```

therefore, if we request a query with 1 result,
the server will send:
1. init + payload
2. complete

but if we request a query with more then 1 result, the server can send diff updates,
and the client can construct the full immutable object over and over.

**how diffing will be done**:
i really liked the [deep-diff](https://www.npmjs.com/package/deep-diff) library,
so i'm thinking of using it and keep the diff as is at the moment.

This is more or less what i had on my mind,
feel free to comment and give feedback :)

### PR DESCRIPTION
**Pull request by DxCx**
TODO:

- [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

Closes #222
Closes #272

### CODE REVIEW

**Comment by stubailo** [comment]
I think this could be really cool! Could you maybe write up a bit of a design about what this is doing and how it changes some of the core packages?

I saw some of the discussion on https://github.com/apollographql/graphql-server/issues/272 but I think it would be great if there was a concise description here of what the transport looks like, how this affects people using the HTTP implementation, etc.

**Comment by DxCx** [comment]
Well @stubailo, i did a short overview in the cast we had, thats why i tought you got it.
Anyway, i do plan writing at least one blog post (or probably more) to help people adopt.

The base protocol is also documented mostly on the issue atm but as you can see i am inteding to format it abit more information and at least add .md under protocol package (adding some basic explanation on apollo docs site, pointing to this md, for those who wants to dig deeper - can be pretty neat)

**Comment by stubailo** [comment]
Yeah my thought was more about the implementation design - I understand the concepts of what it's trying to achieve. Basically it's hard to review the code if there isn't a description of what it's trying to do on an implementation level.

For example, I see that we are including an observable polyfill rather than using RxJS - would it be better to use RxJS instead? It would be interesting to hear about some of the design decisions.

**Comment by DxCx** [comment]
Well, IMO it is worth to use rxjs instead of observable polyfill, it will make code much more readable, however, ive been requested by helfer to support observable the exact same way apollo client does which is with polyfills.

So my hope is that in the future observables will become part of es7 and we can eventually remove all polyfills at least.

Anyway, the ticket was open for discussion for around 2 weeks before i started the implementation, if there are gaps there please write in the issue all the gaps so i can feel them for you and hopefully for everyone else in the future..

**Comment by stubailo** [comment]
Yes I agree completely with everything presented in the issue - the only thing I'm saying is that I'd like to review this but it's over 2000 lines of code. So it would be good to have some help about where to start and what to look at. The issue mostly goes over how it will be used and the protocol, which is great!

**Comment by DxCx** [comment]
Alright,

But the cool thing is that its splitted into packages

So i would not start with a diff but rather with the final branch,
reviewing the new packages, and then look at the small modifications of the
existing files

IMO, this should be the order:
1. Observable
2. Reactive-core
3. Reactive-protocol
4. Websocket

**Comment by MrGekko** [comment]
Is there any way we can progress this pull request? From a quick look it looks good!

**Comment by DxCx** [comment]
Thanks @MrGekko,
Atm we are in CR phase, waiting for @stubailo to give review notes.
hold on a bit i believe this will be merged soon then i'll start work on client side as well.

**Comment by DxCx** [comment]
Replaced by the work done on apollographql/subscriptions-transport-ws#108

**Pull request closed without merging**
