### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by helfer**
It is here!

### CODE REVIEW

**Comment by DxCx** [comment]
hey @helfer if you moved examples per package, why not changing main README.md to just link to them?

**Comment by helfer** [comment]
@DxCx yeah, we could do that. I don't think it's necessary though. I still kinda like having everything in one place so I don't need to click through links to get to those docs. That also makes them more likely to show up as google search results, I think.

**Comment by DxCx** [comment]
the thinking behaind this is README duplication :)
imagine that now every update should be twice

**Comment by helfer** [comment]
après moi, le déluge :wink:

**Comment by stubailo** [comment]
I can't speak that language!!!

Anyway, awesome, so glad to see version numbers that don't start with 0 🎉

**Pull request merged**
