### PR TITLE
generic options resolve function

### PR DESCRIPTION
**Pull request by DxCx**
will be taken out of #308

TODO:

- [ ] Update CHANGELOG.md with your change (include reference to issue & this PR) - not needed i assume?
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by DxCx** [comment]
@helfer / @stubailo ?

**Comment by helfer** [comment]
Looks good to me @DxCx! Is this so it can be used with subscriptions more easily?

**Comment by DxCx** [comment]
Yep

**Comment by DxCx** [comment]
@helfer?

**Pull request merged**
