### PR TITLE
Pass through unknown errors

### LINKED ISSUE #313: `graphqlExpress` swallows an error thrown in a resolver
In express application when my resolver throws an error, `graphql-server-express` hangs. It doesn't respond and doesn't throw an error.

I've dug a little and it looks like I've found the reason. The error thrown here: https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L40 will not be caught and will not be passed through, because `express` expects using `next` callback with error object passed.

> If you pass anything to the next() function (except the string 'route'), Express regards the current request as being in error and will skip any remaining non-error handling routing and middleware functions.

(from here: http://expressjs.com/en/guide/error-handling.html)

So actually I could easily create a pull-request, but when I started taking a look at the tests, I found out that there's a central test, that covers all the frameworks. So it should be fixed for all the server frameworks, so the scope is quite wide.

So I would propose to define the proper behaviour first. Actually there are two options:
1. To pass an error through to be caught outside of graphql middleware
2. To respond with 500, because schema doesn't seem to be valid (as resolver doesn't work properly)

I would prefer the first option, because then it'll be easier to log it depending on developer's preference.

### PR DESCRIPTION
**Pull request by trotzig**
This is still WIP (I have to leave to pick up my kid from preschool). I'll continue working on this tomorrow, but I wanted to get a few eyes on it to see if I'm heading in the right direction. 

Closes #313

### CODE REVIEW

**Comment by DxCx** [comment]
Looks Good! can you please also check out the rest of the integrations as well to make sure all of them handles correctly?

**Comment by trotzig** [comment]
Sure thing, I'll continue tomorrow. I'll attempt to come up with a repro case in a unit test as well. 

The travis failures don't seem related to my change. I saw something similar locally, and I tried to find a fix for it. But after a few `lerna bootstrap` it went away, I haven't figured out why.

**Comment by DxCx** [comment]
hmm if that will be the blocker for the PR i'll step in and debug it no worries you can focus on the PR itself ;)

**Comment by trotzig** [comment]
@DxCx Given the lack of test coverage for the other server plugins, I feel hesitant making any changes there without first investing in setting up tests. It would take me quite a while to figure out how to get that started (I have no experience with other servers than express), and I don't have much spare time at the moment. I could make guesses for how the code should look like, but I'm likely to get something wrong. 

And thanks for offering to debug the travis issue, you're probably in a better position to fix things. 👍

**Comment by DxCx** [comment]
@helfer how do you want to tackle this?

**Comment by DxCx** [comment]
@trotzig fixed it, you can rebase ontop of #394

**Comment by trotzig** [comment]
Awesome, thanks! I'll rebase.

**Comment by DxCx** [comment]
Thanks @trotzig

**Pull request merged**
