### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by thebergamo**
The newer versions of npm doesn't support peerDependencies.

### CODE REVIEW

**Comment by nnance** [comment]
@thebergamo we typically like to maintain backward compatibility with node 4.  Can you provide documentation of peer dependencies being removed?  I can't seem to find any.

**Comment by DxCx** [comment]
as far as i know `peerDependencies` is not removed but is optional and not mandatory.
i agree with @nnance that we should keep it unless you can get here some reference about being deprecated.. we just make sure we are compatible with the newer version as well.

**Comment by helfer** [comment]
Maybe we could follow the approach outlined [here](https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/) and add it both as a dependency and a peerDependency.

**Comment by thebergamo** [comment]
@nnance In npm@3 peerDependencies are not installed by default since npm@1 && npm@2 does[1]. Its make a little confusion in some cases, because you're installing Apollo and graphql is a required dependencies (declared in a peerDependencies), because without that you don't running the server.

Why not just bundled `graphql` with the server? Just declaring it as a dependency we avoid some problems like broken versions of the dependency. 

[1] - https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by helfer** [comment]
@thebergamo for this PR to have any chance of being merged, the first step would be to make the CI tests pass.

**Comment by thebergamo** [comment]
@helfer I will resolve this issues by the morning (GMT +3)

**Comment by helfer** [comment]
@thebergamo if you're still interested in this PR, please let us know! Otherwise we'll probably close it.

**Comment by thebergamo** [comment]
Sorry, a lot of things in this half time. But you can close it.

**Pull request closed without merging**
