### PR TITLE
Allow GraphiQLOptions to be a function

### PR DESCRIPTION
**Pull request by NeoPhi**
This is a proposed implementation to address #418.

TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
@NeoPhi Thanks, looks good but one of the tests that you added currently fails on Node 8. Can you look into that?

**Comment by helfer** [comment]
Also @NeoPhi would you mind rebasing on the new master so we can merge it? 🙏

**Comment by NeoPhi** [comment]
@helfer I think this is ready now.

**Comment by helfer** [comment]
Ok, lgtm @NeoPhi!

**Pull request merged**
